services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AIRSTATION_PLAYER_TITLE=${AIRSTATION_PLAYER_TITLE}
    ports:
      - "7331:7331"
    volumes:
      - /mnt/md0/airstation/airstation-data:/app/storage
      - /mnt/md0/airstation/static:/app/static
    restart: unless-stopped
    env_file:
      - stack.env
